{
    "success": true,
    "message": "All orphans retrieved",
    "data": [
        {
            "orphanId": 2,
            "orphanName": "ahram",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "begom",
            "orphanMotherName": "muklima",
            "orphanAddress": "sylhet",
            "guardianName": "amen",
            "guardianRelationship": "mother",
            "guardianMobile": "01405162101",
            "guardianNid": "16513210325",
            "currentSchoolName": "pdb high school",
            "orphanClassGrade": "10",
            "previousSchoolName": "",
            "typeOfSupport": "FOOD",
            "currentSituation": "sdfasdf",
            "orphanDpUrl": "https://dummy-url.com/photo.jpg",
            "birthCertificateUrl": "https://dummy-url.com/birth.jpg",
            "fatherDeathCertificateUrl": "https://dummy-url.com/death.jpg",
            "orphanViaName": "Direct",
            "orphanViaContact": "N/A",
            "orphanStatus": "APPROVED",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-20T18:35:09.836655",
            "updatedAt": "2026-01-25T00:05:15.670523"
        },
        {
            "orphanId": 10,
            "orphanName": "test",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "test",
            "orphanMotherName": "test",
            "orphanAddress": "test",
            "guardianName": "test",
            "guardianRelationship": "test",
            "guardianMobile": "01405162101",
            "guardianNid": "01405162101",
            "currentSchoolName": "test",
            "orphanClassGrade": "4",
            "previousSchoolName": "test",
            "typeOfSupport": "string",
            "currentSituation": "can't walk",
            "orphanDpUrl": "3637acc8-341c-41e6-bc9f-8bde74753536.jpg",
            "birthCertificateUrl": "097f0607-e062-48ae-8016-51e3f13b347f.pdf",
            "fatherDeathCertificateUrl": "097f0607-e062-48ae-8016-51e3f13b347f.pdf",
            "orphanViaName": "test",
            "orphanViaContact": "01405162101",
            "orphanViaAddress": "test",
            "orphanViaRelation": "test",
            "orphanStatus": "APPROVED",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-22T23:13:08.217561",
            "updatedAt": "2026-01-25T15:40:31.952057"
        },
        {
            "orphanId": 12,
            "orphanName": "মোহাম্মদ হাসান আলী",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "মোহাম্মদ রফিক উদ্দিন",
            "orphanMotherName": "রেহানা বেগম",
            "orphanAddress": "গ্রাম: চরনদীপুর ডাকঘর: নন্দীপাড়া থানা: সদর জেলা: কুমিল্লা",
            "guardianName": "আব্দুল করিম",
            "guardianRelationship": "মামা",
            "guardianMobile": "০১৮৯৮৭৬৫৪৩২",
            "guardianNid": "1234567890123",
            "currentSchoolName": "নন্দীপাড়া সরকারি প্রাথমিক বিদ্যালয়",
            "orphanClassGrade": "পঞ্চম",
            "previousSchoolName": "চতুর্থ শ্রেণি পর্যন্ত নিয়মিত পড়াশোনা করেছে",
            "typeOfSupport": "EDUCATION",
            "currentSituation": "শিশুটির বাবা মৃত্যুবরণ করেছেন। মা অসুস্থ এবং নিয়মিত কাজ করতে পারেন না। পরিবারের আয় খুব সীমিত। শিশুটি পড়াশোনা চালিয়ে যেতে চায় কিন্তু অর্থনৈতিক সমস্যার কারণে ঝুঁকিতে আছে। খাবার ও চিকিৎসা সহায়তা প্রয়োজন।",
            "orphanDpUrl": "7618cba5-58c9-40b0-b323-d36966d6d315.png",
            "birthCertificateUrl": "fdb34a3b-24e0-456b-9d8d-95d17dcdc4d7.pdf",
            "fatherDeathCertificateUrl": "a812c1eb-adc3-4435-aa06-72c4051d826a.pdf",
            "orphanViaName": "নাসির উদ্দিন",
            "orphanViaContact": "০১৯২২৩৩৪৪৫৫",
            "orphanViaAddress": "বাজার রোড, সদর, কুমিল্লা",
            "orphanViaRelation": "পরিচিত",
            "orphanStatus": "APPROVED",
            "orphanSource": "WEBSITE",
            "isConnected": true,
            "currentDonorId": 31,
            "currentDonorName": "mahdee hossain",
            "createdAt": "2026-01-24T14:07:33.777748",
            "updatedAt": "2026-01-26T00:03:48.017501"
        },
        {
            "orphanId": 13,
            "orphanName": "fasdf",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "asdfasdf",
            "orphanMotherName": "asdfsf",
            "orphanAddress": "fasdfasd",
            "guardianName": "asfa",
            "guardianRelationship": "fasd42134",
            "guardianMobile": "4123",
            "guardianNid": "1234",
            "currentSchoolName": "fsadf",
            "orphanClassGrade": "asd",
            "previousSchoolName": "afsd",
            "typeOfSupport": "MEDICAL",
            "currentSituation": "fasdfsaf",
            "orphanDpUrl": "840d12df-83d4-4fbd-92b2-31ebfff6b99e.webp",
            "birthCertificateUrl": "dd818459-780a-4b27-b942-9b23d1baa86e.png",
            "fatherDeathCertificateUrl": "5f5aee9f-46a5-484c-9b4d-b113196d92e2.png",
            "orphanViaName": "asdf",
            "orphanViaContact": "asdf",
            "orphanViaAddress": "afsd",
            "orphanViaRelation": "fasdf",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-24T14:24:05.184842",
            "updatedAt": "2026-01-24T14:24:05.18486"
        },
        {
            "orphanId": 14,
            "orphanName": "asdfas",
            "orphanAge": 1,
            "orphanGender": "MALE",
            "orphanFatherName": "asdf",
            "orphanMotherName": "asdf",
            "orphanAddress": "asdf",
            "guardianName": "fasdf",
            "guardianRelationship": "asdf",
            "guardianMobile": "afsdf",
            "guardianNid": "asdf",
            "currentSchoolName": "asdf",
            "orphanClassGrade": "asd",
            "previousSchoolName": "aasdf",
            "typeOfSupport": "FOOD",
            "currentSituation": "asdfasd",
            "orphanDpUrl": "1f423f99-9552-47a9-a625-91e4e0608e32.png",
            "birthCertificateUrl": "2a891b39-0bd7-4e17-b5b3-45cc10872afa.png",
            "fatherDeathCertificateUrl": "8bc4fdae-96d7-42c7-a9c1-b78baff0d7b1.jpeg",
            "orphanViaName": "asdf",
            "orphanViaContact": "asdf",
            "orphanViaAddress": "asd",
            "orphanViaRelation": "fasd",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-24T14:36:27.47493",
            "updatedAt": "2026-01-24T14:36:27.474946"
        },
        {
            "orphanId": 17,
            "orphanName": "test volluner orphan",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "",
            "orphanMotherName": "",
            "orphanAddress": "",
            "orphanDob": "2026-01-15",
            "orphanContact": "",
            "guardianName": "test volluner orphan",
            "guardianRelationship": "test volluner orphan",
            "guardianMobile": "test volluner orphan",
            "guardianNid": "",
            "currentSchoolName": "test volluner orphan",
            "orphanClassGrade": "test volluner orphan",
            "previousSchoolName": "",
            "orphanEducationInstitute": "",
            "orphanEducationLevel": "",
            "orphanEducationInstituteAddress": "",
            "typeOfSupport": "",
            "orphanHealthCondition": "test volluner orphan",
            "currentSituation": "test volluner orphan",
            "orphanDpUrl": "a38d810a-8103-4529-a0e9-5c7a2a7c7071.jpeg",
            "birthCertificateUrl": "a45e20fd-a769-453a-8965-70c5809accea.jpeg",
            "fatherDeathCertificateUrl": "13967369-ec5b-46b3-a89d-1ef02e0d188d.jpeg",
            "orphanViaName": "",
            "orphanViaContact": "",
            "orphanViaAddress": "",
            "orphanViaRelation": "",
            "orphanStatus": "APPROVED",
            "orphanSource": "VOLUNTEER",
            "isConnected": false,
            "addedByVolunteerId": 2,
            "addedByVolunteerName": "first volunteer",
            "createdAt": "2026-01-25T01:59:24.554818",
            "updatedAt": "2026-01-25T15:39:09.527519"
        },
        {
            "orphanId": 18,
            "orphanName": "main website test",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "main website test",
            "orphanMotherName": "main website test",
            "orphanAddress": "main website test",
            "guardianName": "main website test",
            "guardianRelationship": "main website test",
            "guardianMobile": "454211",
            "guardianNid": "454211",
            "currentSchoolName": "main website test",
            "orphanClassGrade": "main website test",
            "previousSchoolName": "main website test",
            "typeOfSupport": "FOOD",
            "currentSituation": "main website test",
            "orphanDpUrl": "cbbcaad3-128e-43fe-a2cb-a6467708ff7e.png",
            "birthCertificateUrl": "472cd25e-61f3-4724-a574-446eefc33ee1.png",
            "fatherDeathCertificateUrl": "eb9efa08-d7b7-48a0-a765-7a27ecc762bf.png",
            "orphanViaName": "main website test",
            "orphanViaContact": "2121210",
            "orphanViaAddress": "main website test address",
            "orphanViaRelation": "main website test",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-25T16:31:25.470194",
            "updatedAt": "2026-01-25T16:31:25.470226"
        },
        {
            "orphanId": 19,
            "orphanName": "afd",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "asdf",
            "orphanMotherName": "asdf",
            "orphanAddress": "adsf",
            "guardianName": "aasdf",
            "guardianRelationship": "asdf",
            "guardianMobile": "01213032",
            "guardianNid": " 01213032",
            "currentSchoolName": "asdf",
            "orphanClassGrade": "sixth",
            "previousSchoolName": " 01213032",
            "typeOfSupport": "EDUCATION",
            "currentSituation": "details",
            "orphanDpUrl": "27afecb4-3e02-4678-af5c-fea9862a1c60.png",
            "birthCertificateUrl": "7b080d9a-ed00-404c-a285-40ae401d9a2c.png",
            "fatherDeathCertificateUrl": "e26e9aad-1619-4a6b-b128-19fd0b77cf3f.png",
            "orphanViaName": "asdf",
            "orphanViaContact": "032153102",
            "orphanViaAddress": "aksdf",
            "orphanViaRelation": "asdf",
            "orphanStatus": "APPROVED",
            "orphanSource": "WEBSITE",
            "isConnected": true,
            "currentDonorId": 31,
            "currentDonorName": "mahdee hossain",
            "createdAt": "2026-01-26T00:11:01.830763",
            "updatedAt": "2026-01-26T00:23:56.796666"
        },
        {
            "orphanId": 20,
            "orphanName": "asdf",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "asdf",
            "orphanMotherName": "asdf",
            "orphanAddress": "asdf",
            "guardianName": "asdf",
            "guardianRelationship": "asdf",
            "guardianMobile": "421",
            "guardianNid": "121",
            "currentSchoolName": "asdf",
            "orphanClassGrade": "asdf",
            "previousSchoolName": "asdf",
            "orphanEducationInstituteAddress": "",
            "typeOfSupport": "EDUCATION",
            "orphanHealthCondition": "asdf",
            "currentSituation": "fasd",
            "orphanDpUrl": "dc129e00-e0f6-4ac4-8fff-053148645be5.jpeg",
            "birthCertificateUrl": "9504189c-c44b-41b3-9eaf-2aa924f660b8.jpeg",
            "fatherDeathCertificateUrl": "bbc679fe-df6e-4ede-a95c-8d9ca5811ad2.jpeg",
            "orphanViaName": "asdf",
            "orphanViaContact": "120320",
            "orphanViaAddress": "asdf",
            "orphanViaRelation": "asdf",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-26T01:44:04.232549",
            "updatedAt": "2026-01-26T01:44:04.232621"
        },
        {
            "orphanId": 21,
            "orphanName": "asdf",
            "orphanAge": 9,
            "orphanGender": "MALE",
            "orphanFatherName": "asdf",
            "orphanMotherName": "asdf",
            "orphanAddress": "asdf",
            "guardianName": "asdf",
            "guardianRelationship": "asdf",
            "guardianMobile": "2111",
            "guardianNid": "2111",
            "currentSchoolName": "asdf",
            "orphanClassGrade": "asdf",
            "previousSchoolName": "asdf",
            "orphanEducationInstituteAddress": "asdf",
            "typeOfSupport": "EDUCATION",
            "orphanHealthCondition": "asdf",
            "currentSituation": "\nasdf\n",
            "orphanDpUrl": "3db91bb3-9344-4eaa-a5a8-87ddd74d5037.jpg",
            "birthCertificateUrl": "05e7c91b-5e2b-462c-911b-69f772216bf3.png",
            "fatherDeathCertificateUrl": "0c1c5831-6b52-42a6-9263-ed732bcb25a1.jpeg",
            "orphanViaName": " asdf",
            "orphanViaContact": "211121",
            "orphanViaAddress": " asdf",
            "orphanViaRelation": " asdf",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-26T01:48:09.57215",
            "updatedAt": "2026-01-26T01:48:09.572166"
        },
        {
            "orphanId": 22,
            "orphanName": "asdfasf",
            "orphanAge": 8,
            "orphanGender": "MALE",
            "orphanFatherName": "asdfasf",
            "orphanMotherName": "asdfasf",
            "orphanAddress": "asdfasf",
            "guardianName": "asdfasf",
            "guardianRelationship": "asdfasf",
            "guardianMobile": "1102410",
            "guardianNid": "1102410",
            "currentSchoolName": "asdfasf",
            "orphanClassGrade": "asdfasf",
            "previousSchoolName": "asdfasf",
            "orphanEducationInstituteAddress": "asdfasf",
            "typeOfSupport": "EDUCATION",
            "orphanHealthCondition": "asdfasf",
            "currentSituation": "asdfasf",
            "orphanDpUrl": "5d70e9b5-3347-4283-a9ca-6cd7627fa768.jpg",
            "birthCertificateUrl": "aac501f9-879d-4d8d-b171-8ee8ad3c1eab.jpg",
            "fatherDeathCertificateUrl": "e0650a54-be1b-406e-8214-513b7fe8d279.jpg",
            "orphanViaName": "asdfasf",
            "orphanViaContact": "2013201",
            "orphanViaAddress": "asdfasf",
            "orphanViaRelation": "asdfasf",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-26T01:51:40.368749",
            "updatedAt": "2026-01-26T01:51:40.36876"
        },
        {
            "orphanId": 23,
            "orphanName": "cfasdf",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "cfasdf",
            "orphanMotherName": "cfasdf",
            "orphanAddress": "cfasdf",
            "guardianName": "cfasdf",
            "guardianRelationship": "cfasdf",
            "guardianMobile": "101012",
            "guardianNid": "101012",
            "currentSchoolName": "cfasdf",
            "orphanClassGrade": "cfasdf",
            "previousSchoolName": "cfasdf",
            "orphanEducationInstituteAddress": "cfasdf",
            "typeOfSupport": "EDUCATION",
            "orphanHealthCondition": "cfasdf",
            "currentSituation": "cfasdf",
            "orphanDpUrl": "305ebf20-95a5-453b-8686-db9a57ea23d5.jpg",
            "birthCertificateUrl": "ec005ddd-834e-4bf2-9b3f-3b2960e361b5.jpeg",
            "fatherDeathCertificateUrl": "992780d4-4420-4d89-b719-fcfd729dc4fd.png",
            "orphanViaName": "cfasdf",
            "orphanViaContact": "1012.32",
            "orphanViaAddress": "cfasdf",
            "orphanViaRelation": "cfasdf",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-26T01:59:11.585609",
            "updatedAt": "2026-01-26T01:59:11.585621"
        },
        {
            "orphanId": 24,
            "orphanName": "string",
            "orphanAge": 10,
            "orphanGender": "MALE",
            "orphanFatherName": "string",
            "orphanMotherName": "string",
            "orphanAddress": "string",
            "guardianName": "string",
            "guardianRelationship": "string",
            "guardianMobile": "string",
            "guardianNid": "string",
            "currentSchoolName": "string",
            "orphanClassGrade": "string",
            "previousSchoolName": "string",
            "orphanEducationInstituteAddress": "string",
            "typeOfSupport": "string",
            "orphanHealthCondition": "string",
            "currentSituation": "string",
            "orphanDpUrl": "string",
            "birthCertificateUrl": "string",
            "fatherDeathCertificateUrl": "string",
            "orphanViaName": "string",
            "orphanViaContact": "string",
            "orphanViaAddress": "string",
            "orphanViaRelation": "string",
            "orphanStatus": "PENDING",
            "orphanSource": "WEBSITE",
            "isConnected": false,
            "createdAt": "2026-01-26T02:01:10.477332",
            "updatedAt": "2026-01-26T02:01:10.477343"
        }
    ],
    "timestamp": "2026-01-26T02:05:09.793924861"
}